from django.db import models

# Create your models here.

class trains (models.Model) :
    IDTrain = models.AutoField(primary_key=True)
    Plan = models.CharField(max_length = 400)
    Destination = models.CharField(max_length = 100)
    Datetime= models.CharField(max_length = 30)
    Description = models.CharField(max_length = 450)
    Cover = models.CharField(max_length = 400)
    

    #python3 manage.py migrate
    #python3 manage.py makemigrations
    #python3 manage.py shell
    #from RailExpress.models import trains
    #Train1 = trains(1, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-1.1707905852.png", "Toulouse", "09/04/24 07:00 - 19:30", "Explorez le charme pittoresque de la France en voyageant de la vibrante capitale, Paris, à la ville ensoleillée de Toulouse. À travers notre site de voyage dédié à cette route emblématique, découvrez une multitude d'options pour planifier votre voyage de rêve de Paris à Toulouse.", "https://www.trecobat.fr/wp-content/uploads/2022/07/toulouse-trecobat-constructeur-adobestock.jpg").save()
    #Train2 = trains(2, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-2.1707905959.png", "Metz", "10/04/24 09:00 - 16:00", "Partez à la découverte de Metz, une ville pleine de charme et d'histoire, nichée au cœur de la région de la Lorraine.", "https://media.routard.com/image/60/2/metz.1560602.jpg").save()
    #Train3 = trains(3, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-3.1707906095.png", "Nice", "11/04/24 04:00 - 10:00", " Enfin, atteignez votre destination finale : Nice, la perle de la Côte d'Azur. Détendez-vous sur les plages de galets bordées de palmiers, explorez les ruelles colorées de la vieille ville et goûtez aux délices de la cuisine méditerranéenne dans les restaurants en plein air. Ne manquez pas la célèbre Promenade des Anglais, offrant une vue imprenable sur la mer scintillante et les façades colorées de la ville.", "https://cdn.generationvoyage.fr/2020/05/vue-de-nice.jpg").save()
    #Train4 = trains(4, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-4.1707906152.png", "Lyon", "12/04/24 01:00 - 09:00", " Bienvenue sur RailExpress, en direction de Paris à Lyon, deux villes emblématiques de la France. Que vous planifiiez un voyage d'affaires, des vacances en famille ou une escapade romantique, nous sommes là pour vous guider à travers cette belle aventure.", "https://www.larousse.fr/encyclopedie/data/images/1314872-Lyon.jpg").save()
    #Train5 = trains(5, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-5.1707906196.png", "Bordeaux", "13/04/24 05:00 -  12:45", "Découvrez le charme intemporel de la France en planifiant votre prochain voyage de Paris à Bordeaux avec nous", "https://a.cdn-hotels.com/gdcs/production189/d444/3b7213f7-32a8-4923-bf70-51714fb0945a.jpg?impolicy=fcrop&w=800&h=533&q=medium").save()
    #Train6 = trains(6, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-6.1707906276.png", "Londres", "14/04/24 04:00 - 10:00", "Que ce soit pour un voyage d'affaires rapide ou une escapade touristique prolongée, le trajet en train de Paris à Londres offre une expérience sans pareille, mêlant le charme du vieux monde avec l'excitation de la modernité. Attachez vos ceintures et préparez-vous pour un voyage inoubliable à travers deux des plus grandes capitales européennes.", "https://image-tc.galaxy.tf/wijpeg-2vwiddchtdmjikneztikreggo/london_wide.jpg?crop=0%2C105%2C2000%2C1125&width=1980").save()
    #Train7 = trains(7, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-7.1707906325.png", "Marseille", "15/04/24 01:00 - 07:00", "Embarquez pour une expérience inoubliable à bord du train reliant Paris à Marseille, un voyage qui vous transporte à travers les paysages pittoresques de la France. Dès que vous montez à bord, vous êtes accueilli par le doux murmure du train qui démarre, vous invitant à vous détendre et à profiter du trajet.", "https://www.francecomfort.com/l/fr/library/download/urn:uuid:4744970e-a11a-4ad1-b94c-76c3f3f7a251/marseille+1+zuid+frankrijk+middellandse+zee+strand+vakantie+villa+oude+haven+vieux+port.jpg?scaleType=3&width=1600&height=1000").save()
    #Train8 = trains(8, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-8.1707906420.png", "Nantes", "16/04/24 20:00 - 00:00", "Bienvenue à bord du train en direction de Nantes, une ville où l'histoire se mêle à la modernité, où la douceur de vivre s'accorde avec la richesse culturelle. Installez-vous confortablement dans votre siège et laissez-vous emporter par le doux roulis du train à travers les paysages pittoresques de la France.", "https://institut-superieur-environnement.com/content/uploads/2023/01/nantes-capitale-verte.webp").save()
    #Train9 = trains(9, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-9.1707906468.png", "Strasbourg", "17/04/24 18:30 - 23:45", "Strasbourg, célèbre pour sa beauté architecturale, sa cuisine raffinée et sa riche histoire, vous accueillera à bras ouverts. Découvrez la majestueuse cathédrale, flânez dans les ruelles pavées de la vieille ville et imprégnez-vous de l'atmosphère chaleureuse et accueillante de cette cité cosmopolite.", "https://www.noel.alsace/wp-content/uploads/lei/pictures/223012607-strasbourg-capitale-de-noel-2-1600x900.JPG").save()
    #Train10 = trains(10, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-10.1707906522.png", "Lille", "20/05/24 08:00 - 16:00", "Au fur et à mesure que vous vous rapprochez de Lille, vous sentirez l'excitation monter. Cette ville dynamique et cosmopolite vous attend avec ses rues pavées, ses délicieux plats régionaux et son riche patrimoine culturel.", "https://uploads.lebonbon.fr/source/2023/march/2043048/ville-lille_1_2000.jpg").save()
    #Train11 = trains(11, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-11.1707906569.png", "Montpellier", "21/04/24 03:00 - 06:55", "Pendant votre trajet, profitez des services à bord pour rendre votre voyage aussi agréable que possible. Détendez-vous avec un bon livre, savourez une pause café au wagon-bar ou laissez-vous emporter par les paysages qui défilent tout en écoutant votre musique préférée.", "https://a.cdn-hotels.com/gdcs/production8/d1097/363987af-c07c-4f91-9f4d-847552d055e4.jpg?impolicy=fcrop&w=800&h=533&q=medium").save()
    #Train12 = trains(12, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-12.1707906606.png", "Reims", "22/04/24 12:50 - 14:15", "Embarquez pour une aventure ferroviaire captivante de Paris à Reims, où chaque virage de rail révèle un nouveau chapitre de l'histoire et de la culture françaises. À bord, laissez-vous envoûter par le paysage pittoresque qui défile sous vos yeux, des vastes plaines aux vignobles vallonnés de la région champenoise.", "https://www.reims-tourisme.com/assets/uploads/sites/2/2022/12/cathedrale-c-cyrille-beudot-office-de-tourisme-du-grand-reims-3-1024x683.jpg").save()
    #Train13 = trains(13, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-13.1707906641.png", "Rennes", "23/04/24 22:00 - 05:00", "En chemin vers Rennes, vous aurez l'occasion d'admirer les magnifiques panoramas de la vallée de la Loire, réputée pour ses châteaux majestueux et ses vignobles pittoresques. Laissez-vous séduire par la douce tranquillité des rivières et des villages qui ponctuent votre trajet.", "https://www.tourisme-rennes.com/voy_content/uploads/2023/09/Palais-parlement-bretagne-1-1024x683.jpg").save()
    #Train14 = trains(14, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/metro/plan-de-ligne_metro_ligne-14.1707906674.png", "Angers", "24/04/24 21:30 - 01:55", "Bienvenue à bord du train en direction d'Angers, une ville où l'histoire se mêle harmonieusement à la modernité. Installez-vous confortablement dans votre siège et préparez-vous à un voyage enchanteur à travers les paysages pittoresques de la France.", "https://media.routard.com/image/01/2/fb-angers.1598012.jpg").save()
    #Train15 = trains(15, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/rer/plan-de-ligne_rer_ligne-a.1657062002.png", "Toulon", "25/05/24 04:30 - 7:25", "Embarquez pour une aventure ferroviaire inoubliable depuis la majestueuse ville lumière jusqu'à la splendide côte méditerranéenne. Votre voyage en train de Paris à Toulon promet des panoramas spectaculaires, une immersion dans la diversité culturelle française et une expérience de voyage confortable et relaxante.", "https://partir.ouest-france.fr/magazine/wp-content/uploads/2022/10/lsntnybyltk.jpg").save()
    #Train16 = trains(16, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/rer/plan-de-ligne_rer_ligne-b.1702166426.png", "Dijon", "26/04/24 23:10 - 10:00", "Profitez de ce moment de tranquillité et d'évasion pendant que nous vous conduisons vers votre destination. Nous espérons que votre voyage en train de Paris à Dijon sera une expérience mémorable et que vous en garderez des souvenirs durables.", "https://www.dijon-metropole.fr/wp-content/uploads/sites/25/2023/10/Dijon_Hotel-de-ville_vue-drone%C2%A9ville-de-Dijon_Francois-Weckerle_VD_0049110_BD.jpg").save()
    #Train17 = trains(17, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/rer/plan-de-ligne_rer_ligne-c.1706626525.png", "Grenoble", "27/04/24 04:00 - 05:00", "Dès que le train quitte la gare parisienne, vous êtes enveloppé dans une atmosphère de découverte et d'évasion. Les vastes champs de la campagne française défilent sous vos yeux, parsemés de villages pittoresques et de vignobles luxuriants. Vous pouvez vous laisser envoûter par la tranquillité des paysages ou engager des conversations animées avec vos compagnons de voyage.", "https://www.gix-immobilier.fr/public/files/images/AdobeStock_75656482.jpeg").save()
    #Train18 = trains(18, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/rer/plan-de-ligne_rer_ligne-d.1695733918.png", "Nîmes", "28/04/24 01:10 - 01:55", "Bienvenue à bord du voyage ferroviaire de Paris à Nîmes, une aventure à travers les paysages pittoresques de la France. Installez-vous confortablement dans votre siège et laissez-vous emporter par le charme et la tranquillité du trajet.", "https://www.tourismegard.com/uploads/2022/10/arenes-aerienne-nimes.jpg").save()
    #Train19 = trains(19, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/rer/plan-de-ligne_rer_ligne-e.1695734015.png", "Villeurbanne", "29/05/24 20:00 - 01:00", "Tout au long de notre trajet, vous serez enchanté par la diversité des panoramas qui s'offrent à vous. Des champs verdoyants parsemés de villages pittoresques aux vignobles vallonnés de la Bourgogne, chaque instant est une invitation à l'émerveillement.", "https://static.actu.fr/uploads/2023/04/travaux-gratte-ciel-villeurbanne.png").save()
    #Train20 = trains(20, "https://www.ratp.fr/sites/default/files/lines-assets/plan-de-ligne/busratp/plan-de-ligne_busratp_ligne-253.1695164429.png", "Bruxelles", "30/04/24 08:45 - 18:00", "Que votre séjour à Bruxelles soit le début d'une nouvelle aventure ou le prolongement d'une expérience inoubliable, ce voyage en train aura sûrement éveillé votre passion pour la découverte et l'aventure.", "https://www.visitonsbruxelles.com/f/belgica/bruselas/guia/grand-place.jpg").save()


    # Pour les voir dans la base de données dans le terminal il faut entrer:
    # trains.objects.all()

    # Pour les voir dans la base de données dans le navigateur il faut entrer:
    # http://127.0.0.1:8000/admin