# Generated by Django 5.0.3 on 2024-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train',
            fields=[
                ('IDTrain', models.AutoField(primary_key=True, serialize=False)),
                ('Ligne', models.CharField(max_length=20)),
                ('Image', models.CharField(max_length=400)),
                ('Destination', models.CharField(max_length=100)),
                ('heure_arrivée', models.IntegerField()),
                ('heure_départ', models.IntegerField()),
                ('Description', models.CharField(max_length=300)),
            ],
        ),
    ]
