# Generated by Django 5.0.3 on 2024-03-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RailExpress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='heure_arrivée',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='train',
            name='heure_départ',
            field=models.CharField(max_length=10),
        ),
    ]
