# Generated by Django 5.0.3 on 2024-03-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RailExpress', '0003_trains_delete_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='Datetime',
            field=models.CharField(max_length=30),
        ),
    ]
