# Generated by Django 5.0.3 on 2024-03-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RailExpress', '0004_alter_trains_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='Description',
            field=models.CharField(max_length=450),
        ),
    ]
